# Generated by Django 5.1.6 on 2025-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('citate', models.CharField(max_length=155, verbose_name='Цитата')),
                ('description', models.TextField(verbose_name='Описания О Нас')),
                ('specialization_title', models.CharField(max_length=55, verbose_name='Наши Специальности')),
                ('specialization', models.CharField(max_length=55, verbose_name='Специальности')),
                ('logo', models.ImageField(upload_to='', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('number1', models.CharField(max_length=100, verbose_name='1 Номер')),
                ('number2', models.CharField(max_length=100, verbose_name='2 Номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.Почта')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('send_button', models.CharField(max_length=55, verbose_name='Кнопка Отправить')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Компании')),
            ],
            options={
                'verbose_name': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя Компании')),
                ('phone', models.CharField(max_length=35, verbose_name='Телофонный Номер')),
                ('vertical_text', models.CharField(max_length=100, verbose_name='Вертикальный Текст')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='MainProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото Проэкта')),
                ('project_name', models.CharField(max_length=100, verbose_name='Имя Проэкта')),
                ('project_desription', models.TextField(verbose_name='Описание Проэкта')),
            ],
            options={
                'verbose_name': 'Главные Проэкты',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=55, verbose_name='1 Навигационная Кнопка')),
                ('about', models.CharField(max_length=55, verbose_name='2 Навигационная Кнопка')),
                ('projects', models.CharField(max_length=55, verbose_name='3 Навигационная Кнопка')),
                ('services', models.CharField(max_length=55, verbose_name='4 Навигационная Кнопка')),
                ('contacts', models.CharField(max_length=55, verbose_name='5 Навигационная Кнопка')),
                ('previous_button', models.CharField(max_length=55, verbose_name='Предыдущая Кнопка')),
                ('next_button', models.CharField(max_length=55, verbose_name='Следующая Кнопка')),
                ('look_more_button', models.CharField(max_length=35, verbose_name='Кнопка Смотреть Дальше')),
            ],
            options={
                'verbose_name': 'Навигация',
                'verbose_name_plural': 'Навигации',
            },
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото Проэкта')),
                ('project_name', models.CharField(max_length=100, verbose_name='Названия Проэкта')),
                ('vertical_line', models.CharField(max_length=55, verbose_name='Вертикальная Линия')),
            ],
            options={
                'verbose_name': 'Наши Проэкты',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('years', models.IntegerField(verbose_name='Годы')),
                ('years_title1', models.CharField(max_length=100, verbose_name='Заголовок лет 1')),
                ('years_title2', models.CharField(max_length=100, verbose_name='Заголовок лет 2')),
            ],
            options={
                'verbose_name': 'Наш Сервис',
                'verbose_name_plural': 'Наши сервисы',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
