# Generated by Django 5.1.6 on 2025-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_about_options_alter_footer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='service_description',
            field=models.TextField(default=1, verbose_name='Описания Сервиса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourservices',
            name='service_icon',
            field=models.ImageField(default=1, upload_to='', verbose_name='Иконка сервиса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourservices',
            name='service_title',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок сервиса'),
            preserve_default=False,
        ),
    ]
