# Generated by Django 5.1.6 on 2025-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ourservices_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка Сервиса')),
                ('service_title', models.CharField(max_length=50, verbose_name='Названия Сервиса')),
                ('service_description', models.TextField(verbose_name='Описания Сервиса')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Специальности')),
                ('spec_name', models.CharField(max_length=100, verbose_name='Названия Спец-ти')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='service_icon',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='service_title',
        ),
    ]
