# Generated by Django 5.1.6 on 2025-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_specializations_remove_about_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainprojects',
            old_name='project_desription',
            new_name='project_description',
        ),
    ]
