# Generated by Django 5.1.6 on 2025-03-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
