# Generated by Django 5.1.6 on 2025-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('email', models.TextField()),
            ],
        ),
    ]
